#!/bin/bash
# SPDX-License-Identifier: GPL-2.0

for file in $(find queue-* -type f | grep patch); do
	ISO=$(file "${file}" | grep ISO)
	if [ "${ISO}" != "" ] ; then
		echo "Converting ${file}"
		tmpfile=$(mktemp convert-XXXXX || exit 1)
		iconv -c --to-code=UTF-8//TRANSLIT "${file}" > "${tmpfile}"
		mv "${tmpfile}" "${file}"
	fi
done

