#!/usr/bin/perl

# we make a "fake" message id by taking the current number
# of seconds since the beginning of Unix time and tacking on
# a random number to the end, in case we are called quicker than
# 1 second since the last time we were called.

my $date = `date "+\%s"`;
my $hostname = `hostname -d`;
chomp($date);
my $pseudo_rand = int (rand(4200));
$message_id = "$date$pseudo_rand\@$hostname";
print "$message_id";
