#!/bin/bash

SCRIPT_NAME=`basename ${0}`
MBOX="$1"
if [ "${MBOX}" == "" ] ; then
	echo "ERROR, you must specify a mailbox name."
	echo "usage:"
	echo "    ${SCRIPT_NAME} mailbox_name"
	exit
fi

FULL_VERSION=`ketchup -m`
BASE_VERSION=${FULL_VERSION/-rc?/}
DATE=`date -u --date="2 days"`

if [ ${FULL_VERSION} == ${BASE_VERSION} ] ; then
	echo "Makefile says the version is ${FULL_VERSION}, did you forget to set the -rc version?"
	exit
fi

if [ ! -f "diffstat" ] ; then
	echo "You forgot to create the 'diffstat' file, please do that first."
	exit
fi

echo "Creating the mailbox for kernel release ${FULL_VERSION}"

TMPFILE=`mktemp stable_header.XXXXXX` || exit 1
NUM_PATCHES=`quilt series | wc -l`

(
echo "This is the start of the stable review cycle for the ${BASE_VERSION} release."
echo "There are ${NUM_PATCHES} patches in this series, all will be posted as a response"
echo "to this one.  If anyone has any issues with these being applied, please"
echo "let me know."
echo ""
echo "Responses should be made by ${DATE}."
echo "Anything received after that time might be too late."
echo ""
echo "The whole patch series can be found in one patch at:"
echo "	kernel.org/pub/linux/kernel/v3.0/stable-review/patch-${FULL_VERSION}.gz"
echo "and the diffstat can be found below."
echo ""
echo "thanks,"
echo ""
echo "greg k-h"
echo ""
echo "-------------"
echo "Shortlog of commits:"
echo ""
stable-shortlog
echo ""
echo "-------------"
echo ""
echo "Diffstat:"
echo ""

cat diffstat
) > ${TMPFILE}

FROM="Greg KH <gregkh@linuxfoundation.org>"
TO="linux-kernel@vger.kernel.org, stable@vger.kernel.org"
#CC="torvalds@linux-foundation.org, akpm@linux-foundation.org, alan@lxorguk.ukuu.org.uk"
CC=""
SUBJECT="${BASE_VERSION}-stable review"

quilt mail --mbox ${MBOX}	\
	-m "$(cat ${TMPFILE})"	\
	--sender "${FROM}"	\
	--from "${FROM}"	\
	--to "${TO}"		\
	--cc "${CC}"		\
	--prefix ""		\
	--subject "${SUBJECT}"

rm ${TMPFILE}
echo "mbox is now in ${MBOX}"

echo "Add:"
echo "Cc: torvalds@linux-foundation.org, akpm@linux-foundation.org, alan@lxorguk.ukuu.org.uk"
echo "to the first email."

#q mail --mbox x -m "$(cat ../stable-queue/00)" --sender gregkh@lf.org --from gregkh@lf.org --to foo@foo --subject "This is the subject"

